# Generated by Django 5.0.7 on 2026-08-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(help_text='e.g. 2026, 2025, 2024, Ongoing, 2023–24', max_length=50)),
                ('title', models.CharField(help_text='Achievement title', max_length=255)),
                ('subtitle', models.CharField(blank=True, help_text='Achievement subtitle or detail', max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='general', max_length=100)),
                ('key_identifier', models.CharField(blank=True, help_text="Optional identifier for dynamic sync (e.g. 'dsa_solved', 'coding_streak')", max_length=100, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CodingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(help_text='e.g. GitHub, GeeksforGeeks, LeetCode, LinkedIn', max_length=100)),
                ('username', models.CharField(help_text='e.g. @saurabhmaurpx2', max_length=100)),
                ('profile_url', models.URLField(max_length=500)),
                ('description', models.CharField(blank=True, help_text='e.g. Algorithmic problem solving, Growing Network of', max_length=255, null=True)),
                ('problems_solved', models.IntegerField(blank=True, help_text='Numeric count of problems solved (e.g. 400)', null=True)),
                ('star_rating', models.CharField(blank=True, help_text='e.g. 4-Star', max_length=50, null=True)),
                ('coding_streak_days', models.IntegerField(blank=True, help_text='Numeric count of streak days (e.g. 185)', null=True)),
                ('followers_count', models.IntegerField(blank=True, help_text='Numeric count of followers (e.g. 6700)', null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProfileStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_air', models.CharField(default='7409', help_text='e.g. 7409', max_length=50)),
                ('gate_score', models.CharField(default='503', help_text='e.g. 503', max_length=50)),
                ('gate_qualifications_count', models.IntegerField(default=2)),
                ('projects_built_count', models.IntegerField(default=10)),
                ('internships_completed_count', models.IntegerField(default=1)),
                ('off_campus_offers_count', models.IntegerField(default=1)),
                ('cgpa', models.CharField(default='8.46', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile Stats',
                'verbose_name_plural': 'Profile Stats',
            },
        ),
    ]
